---
title: "Report Sample"
author: "Eric Miller"
date: '`r Sys.Date()`'
format:
  html:
    code-fold: true
course: STA 6257 - Advanced Statistical Modeling
bibliography: references.bib # file contains bibtex for references
#always_allow_html: true # this allows to get PDF with HTML features
self-contained: true
execute: 
  warning: false
  message: false
editor: 
  markdown: 
    wrap: 72
---

## Introduction

Support Vector Machines (SVM) are a useful way to mine data given their effectiveness for binary classification. SVMs can also be utilized to make models that can ingest new data to make accurate predictions on a variety of initiatives, such as Electronic Medical Records (EMR). It is important to keep in mind, though, that SVMs can be hard to train, especially on big data sets which are often the case in the Healthcare industry. SVMs can also be responsive to how the SVM kernel and hyperparameters are chosen as they rely on a definitive Hyperplane. Therefore, is important to cleanse and feature engineer the data, which will help make new features that may be more useful for the SVM model. Once the SVM model has been trained and tuned, it can be used to predict an outcome with a specific degree of certainty with new data. The subsequent paper focuses on the development and utilization of SVMs to predict Intensive Care Unit (ICU) patient survivability.

# Research

## Week 2

{{< include "Research/Week 2.md" >}}

## Week 3

{{< include "Research/Week 3.md" >}}

## Week 4 

{{< include "Research/Week 4.md" >}}

## Methods

## Analysis and Results

### Data and Vizualisation

### Statistical Modeling

### Conlusion

## References
